obstacle_range: 10
raytrace_range: 15
footprint: [[-1.3, -2.75], [-1.3, 2.75], [1.3, 2.75], [1.3, -2.75]]
#robot_radius: ir_of_robot
inflation_radius: 1

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: wamv/lidar_wamv_link, data_type: LaserScan, topic: wamv/sensors/laser/scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: wamv/lidar_wamv_link, data_type: PointCloud, topic: wamv/sensors/lidars/lidar_wamv/points, marking: true, clearing: true}
