local_costmap:
  global_frame: wamv/odom
  robot_base_frame: wamv/base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.1
