thrusters:
  - name: "left1"
    position: "0 0 0"
    orientation: "0 0 0"
    topic: "/wamv/thrusters/left_thrust_cmd"
  - name: "left2"
    position: "1 1 1"
    orientation: "2 2.3 2"
    topic: "/wamv/thrusters/left2_thrust_cmd"
  - name: "right1"
    position: "3 3 3"
    orientation: "4 4.2 4"
    topic: "/wamv/thrusters/right2_thrust_cmd"
  - name: "right2"
    position: "5 5 5"
    orientation: "6 6.7 6"
    topic: "/wamv/thrusters/right_thrust_cmd"
